"use client";
import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "../../../lib/supabase";

const PRIORITY_CONFIG: Record<string,{label:string;bg:string;color:string;border:string}> = {
  low:      { label: "נמוכה",   bg: "bg-blue-50",   color: "text-blue-700",   border: "border-blue-100"   },
  medium:   { label: "בינונית", bg: "bg-yellow-50",  color: "text-yellow-700", border: "border-yellow-100" },
  high:     { label: "גבוהה",   bg: "bg-orange-50",  color: "text-orange-700", border: "border-orange-100" },
  critical: { label: "קריטי",   bg: "bg-red-50",     color: "text-red-700",    border: "border-red-200"    },
};
const TYPE_ICONS:Record<string,string>={contract_expiry:"📄",option_deadline:"⏰",guarantee_expiry:"<���",insurance_expiry:"<���️",safety_inspection:"🔒",payment_pending:"<���",system:"⚙o��",other:"🔔"};function fmtDate(d:string){if(!d)return"—";return new Date(d).toLocaleDateString("he-IL");}
export default function AlertsPage(){const router=useRouter();const [alerts,setAlerts]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [filterP,setFilterP]=useState("all");const [filterType,setFilterType]=useState("all");const [filterHandled,setFilterHandled]=useState(false);const [selected,setSelected]=useState<Set<string>>(new Set());const [bulkLoading,setBulkLoading]=useState(false);useEffect(function(){load();},[filterHandled]);async function load(){setLoading(true);let q=supabase.from("alerts").select("*").order("created_at",{ascending:false});if(!filterHandled)q=q.eq("is_handled",false);const{data}=await q;setAlerts(data??[]);setLoading(false);}async function markHandled(id:string,handled:boolean){await supabase.from("alerts").update({is_handled:handled,handled_at:handled?new Date().toISOString():null}).eq("id",id);await load();}async function bulkHandle(){if(selected.size===0)return;setBulkLoading(true);await supabase.from("alerts").update({is_handled:true,handled_at:new Date().toISOString()}).in("id",Array.from(selected));setSelected(new Set());setBulkLoading(false);await load();}async function deleteAlert(id:string){if(!confirm("למחוק התראה?"))return;await supabase.from("alerts").delete().eq("id",id);await load();}function toggleSelect(id:string){setSelected(function(prev){const next=new Set(prev);if(next.has(id))next.delete(id);else next.add(id);return next;});}function navigateToEntity(a:any){const routes:Record<string,string>={contract:"/contracts",guarantee:"/guarantees",insurance:"/insurances",safety:"/safety",charge:"/payments"};router.push(routes[a.related_entity_type??""]??"/dashboard");}const filtered=alerts.filter(function(a){return(filterP==="all"||a.priority===filterP)&&(filterType==="all"||a.alert_type===filterType);});return(<div dir="rtl"><h1 className="text-3xl font-bold">התראות</h1></div>);}
